# Generated by Django 3.1.1 on 2021-01-15 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('team_management', 'Can create, assign and delete project')]},
        ),
    ]
